version: '3.8'

services:
  web:
    build: 
      context: ..
      dockerfile: deployment/Dockerfile
    restart: always
    depends_on:
      - redis
    environment:
      - SECRET_KEY=${SECRET_KEY:-changeme}
      - SESSION_COOKIE_SECURE=${SESSION_COOKIE_SECURE:-false}
      - SESSION_TIMEOUT=${SESSION_TIMEOUT:-3600}
      - SESSION_CLEANUP_INTERVAL=${SESSION_CLEANUP_INTERVAL:-3600}
      - REDIS_URL=redis://redis:6379/0
      - GUNICORN_WORKERS=${GUNICORN_WORKERS:-4}
      - GUNICORN_TIMEOUT=${GUNICORN_TIMEOUT:-120}
    volumes:
      - ../uploads:/app/uploads
      - ../outputs:/app/outputs
      - ../logs:/app/logs
    command: gunicorn -c gunicorn.conf.py wsgi:app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 30s
      timeout: 10s
      retries: 3
    expose:
      - 5000

  worker:
    build: 
      context: ..
      dockerfile: deployment/Dockerfile
    restart: always
    depends_on:
      - redis
    environment:
      - SECRET_KEY=${SECRET_KEY:-changeme}
      - REDIS_URL=redis://redis:6379/0
    volumes:
      - ../uploads:/app/uploads
      - ../outputs:/app/outputs
      - ../logs:/app/logs
    command: python run.py --worker

  redis:
    image: redis:alpine
    restart: always
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

  nginx:
    image: nginx:alpine
    restart: always
    depends_on:
      - web
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../static:/app/static:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
      - nginx_logs:/var/log/nginx
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  redis_data:
  nginx_logs: 